// src/renderer/components/Poster.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';

import { Metadata } from '../../common/api/metadata';

export interface PosterProps {
  items: Metadata[];
}

export class Poster extends React.Component<PosterProps, {}> {

  render() {
    return this.props.items.map((item, i) => (
      <div className="react-item movie" key={i}>
        <div className="front">
          <Link to={`/media/${item.type}/${item.tmdb}`}>
            {item.poster &&
              <div className="front-image" style={{ backgroundImage: `url(${item.poster})` }}>
                <div className="backdrop medium">
                  <div className="react-play-button fill">
                    <figure className="icon-content" />
                  </div>
                </div>
              </div>
            }
          </Link>
        </div>
      </div>
    ));
  }

}

// src/renderer/app/components/poster/poster.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-poster',
  templateUrl: './poster.component.html',
  styleUrls: ['./poster.component.css'],
})
export class PosterComponent {

  @Input() readonly items: any[];

  protected showTooltip() {}

  protected dismissTooltipDelay() {}

}

<ng-container *ngFor="let item of items">
  <div class="react-item movie">
    <div class="front" (mouseenter)="showTooltip($event)" (mouseleave)="dismissTooltipDelay($event)">
      <a routerLink="/media/{{item.type}}/{{item.tmdb}}">
        <ng-container *ngIf="!!item.poster">
          <div class="front-image" [style.background-image]="url(item.poster)">
            <div class="backdrop medium">
              <div class="react-play-button fill">
                <figure class="icon-content"></figure>
              </div>
            </div>
          </div>
        </ng-container>
      </a>
    </div>
  </div>
</ng-container>
