// src/renderer/app/components/carousel/carousel.component.ts
import { Component, Input, AfterViewInit, ViewChild, ElementRef } from '@angular/core';

export class CarouselComponentState {
  navPrevDisabled!: boolean;
  navNextDisabled!: boolean;
  startPoint!: number;
  itemsShownTotal!: number;
  itemWidth!: number;
  innerWidth!: number;
  itemsFitSlide!: number;
  itemsLength!: number;
}

@Component({
  selector: 'app-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.css'],
})
export class CarouselComponent extends CarouselComponentState implements AfterViewInit {

  @ViewChild('poster') poster: ElementRef;

  @ViewChild('wrapper') wrapper: ElementRef;

  @Input() readonly items: any[];

  @Input() readonly route?: string;

  @Input() readonly title?: string;

  ngAfterViewInit() {
    this.updateCarousel();
    window.addEventListener('resize', () => this.updateCarousel(), false);
  }

  updateCarousel() {
    const posterItems = this.poster.nativeElement.querySelectorAll('.react-item');
    const posterItem = this.poster.nativeElement.querySelector('.react-item');
    const startPoint = 0; // parseInt(this.poster.nativeElement.style.marginLeft, 10);
    const maxw = this.wrapper.nativeElement.offsetWidth;

    const itemsFitSlide = Array.from(posterItems).filter((item: HTMLElement) => {
      const rect = item.getBoundingClientRect();

      return rect.left < maxw;
    }).length;


    setTimeout(() => {
      this.navPrevDisabled = true;
      this.innerWidth = -startPoint;
      this.startPoint = -startPoint;
      this.itemsShownTotal = itemsFitSlide;
      this.itemWidth = posterItem.getBoundingClientRect().width;
      this.navNextDisabled = itemsFitSlide === posterItems.length;
      this.itemsLength = posterItems.length;
      this.itemsFitSlide = itemsFitSlide;

      console.log(this);
    }, 7);
  }

  // @TODO: Fix itemWidth
  handlePrev() {
    const itemsLeft = +Math.abs(this.itemsFitSlide - this.itemsShownTotal);
    const firstSlide = itemsLeft <= this.itemsFitSlide;

    this.innerWidth = !firstSlide
      ? this.innerWidth + (this.itemWidth * this.itemsFitSlide)
      : this.startPoint;

    this.itemsShownTotal = !firstSlide
      ? this.itemsShownTotal - this.itemsFitSlide
      : this.itemsFitSlide;

    this.navPrevDisabled = firstSlide;
    this.navNextDisabled = false;
  }

  // @TODO: Fix itemWidth
  handleNext() {
    const itemsLeft = this.itemsLength - this.itemsShownTotal;
    const lastSlide = this.itemsFitSlide > itemsLeft;

    this.innerWidth = !lastSlide
      ? -Math.abs(this.innerWidth - (this.itemWidth * this.itemsFitSlide))
      : -Math.abs(this.innerWidth - (this.itemWidth * itemsLeft));

    this.itemsShownTotal = !lastSlide
      ? this.itemsShownTotal + this.itemsFitSlide
      : this.itemsShownTotal + itemsLeft;

    this.navPrevDisabled = false;
    this.navNextDisabled = this.itemsShownTotal === this.itemsLength;
  }

}

<section class="block collection portrait carousel">
  <div class="scaffold">
    <i class="navigation prev whiteframe" [class.disabled]="navPrevDisabled" (click)="handlePrev()"></i>
    <i class="navigation next whiteframe" [class.disabled]="navNextDisabled" (click)="handleNext()"></i>
    <header class="collection-header">
      <ng-container *ngIf="route; else showTitle">
        <a routerLink="{{ route }}">
          <div>
            <span class="see-all button">{{ 'show.more' | translate }}</span>
            <h2>{{ title }}</h2>
          </div>
        </a>
      </ng-container>
      <ng-template #showTitle>
        <h2>{{ title }}</h2>
      </ng-template>
    </header>
    <div class="carousel-wrapper" #wrapper>
      <div class="carousel-inner use-transition" [style.transform]="'translateX('+ innerWidth +'px)'">
        <div #poster>
          <app-poster [items]="items"></app-poster>
        </div>
      </div>
    </div>
  </div>
</section>

// src/renderer/components/Carousel.tsx
import * as React from 'react';
import * as classNames from 'classnames';
import * as $ from 'jquery';
import { Link } from 'react-router-dom';
import { translate, InjectedTranslateProps } from 'react-i18next';

import { Metadata } from '../../common/api/metadata';
import { Poster } from './Poster';
import {
  Scaffold,
  BlockCollection,
  CollectionHeader,
  HeaderButton
} from './Items';

const initialState = {  };

export interface CarouselProps extends InjectedTranslateProps {
  route?: string;
  title?: string;
  items: Metadata[]
}

export interface CarouselState {
  navPrevDisabled: boolean;
  navNextDisabled?: boolean;
  startPoint?: number;
  itemsShownTotal?: number;
  itemWidth?: number;
  innerWidth?: number;
  itemsFitSlide?: number;
  itemsLength?: number;
}

export class CarouselComp extends React.Component<Partial<CarouselProps>, CarouselState> {

  wrapper!: HTMLElement;
  items!: HTMLElement;

  readonly state: CarouselState = {
    navPrevDisabled: true,
  };

  componentDidMount() {
    this.updateCarousel();
  }

  private updateCarousel() {
    const $reactItems = $(this.items).find('.react-item');
    const maxw = $(this.wrapper).width();

    const itemsFitSlide = $reactItems.filter(function() {
      return $(this).position().left < maxw
    }).length;

    const startPoint = parseInt($reactItems.css('margin-left'));

    this.setState({
      navPrevDisabled: true,
      innerWidth: -startPoint,
      startPoint: -startPoint,
      itemsShownTotal: itemsFitSlide,
      itemWidth: $reactItems.outerWidth(true),
      navNextDisabled: itemsFitSlide === $reactItems.length,
      itemsLength: $reactItems.length,
      itemsFitSlide,
    });
  }

  private handlePrev = () => {
    const { state } = this;

    let innerWidth = state.innerWidth + (state.itemWidth * state.itemsFitSlide);
    const itemsLeft = +Math.abs(state.itemsFitSlide - state.itemsShownTotal);

    let firstSlide = false;
    if (itemsLeft <= state.itemsFitSlide) {
      firstSlide = true;
      innerWidth = state.startPoint;
    }

    const itemsShownTotal = firstSlide
      ? state.itemsFitSlide
      : state.itemsShownTotal - state.itemsFitSlide;

    this.setState({
      navPrevDisabled: firstSlide,
      navNextDisabled: false,
      itemsShownTotal,
      innerWidth,
    });

    return false;
  };

  private handleNext = () => {
    const { state } = this;

    let innerWidth = -Math.abs(state.innerWidth - (state.itemWidth * state.itemsFitSlide));

    const itemsLeft = state.itemsLength - state.itemsShownTotal;
    const lastSlide = state.itemsFitSlide > itemsLeft;

    if (lastSlide) {
      innerWidth = -Math.abs(state.innerWidth - (state.itemWidth * itemsLeft));
    }

    const itemsShownTotal = lastSlide
      ? state.itemsShownTotal + itemsLeft
      : state.itemsShownTotal + state.itemsFitSlide;

    this.setState({
      navPrevDisabled: false,
      navNextDisabled: itemsShownTotal === state.itemsLength,
      itemsShownTotal,
      innerWidth,
    });

    return false;
  };

  private createCollectionHeader = () => (
    <CollectionHeader>
      {this.props.route ? (
        <Link to={this.props.route}>
          <span>
            <HeaderButton>{this.props.t('show.more')}</HeaderButton>
            <h2>{this.props.title}</h2>
          </span>
        </Link>
      ) : (
        <h2>{this.props.title}</h2>
      )}
    </CollectionHeader>
  );

  render() {
    const { state, props } = this;

    const nav = {
      prev: classNames('navigation prev whiteframe', {
        disabled: state.navPrevDisabled,
      }),
      next: classNames('navigation next whiteframe', {
        disabled: state.navNextDisabled,
      }),
    };

    return (
      <BlockCollection className="portrait carousel">
        <Scaffold>
          <i className={nav.prev} onClick={this.handlePrev} />
          <i className={nav.next} onClick={this.handleNext} />
          {this.createCollectionHeader()}
          <div className="carousel-wrapper" ref={ref => this.wrapper = ref}>
            <div className="carousel-inner use-transition" style={{transform: `translateX(${state.innerWidth}px)`}}>
              <div ref={ref => this.items = ref}>
                <Poster items={props.items}/>
              </div>
            </div>
          </div>
        </Scaffold>
      </BlockCollection>
    );
  }

}

export const Carousel = translate()(CarouselComp);
