// src/renderer/components/Header.tsx
import * as React from 'react';
import { translate, InjectedTranslateProps } from 'react-i18next';
import { NavLink } from 'react-router-dom';
import { ipcRenderer } from 'electron';
import { observer, inject } from 'mobx-react';
import * as classNames from 'classnames';

import { SearchStore } from 'src/renderer/stores/search.store';

export interface HeaderState {
  hoverActive: boolean;
}

export interface HeaderProps extends InjectedTranslateProps {
  search: SearchStore;
}

@translate()
@inject(['search', 'user'])
@observer
export class Header extends React.Component<HeaderProps, HeaderState> {

  state = {
    hoverActive: false,
  };

  private hoverDetails = () => {
    this.setState({
      hoverActive: !this.state.hoverActive
    });
  }

  private quitApp = () => ipcRenderer.emit('appQuit');

  render() {
    const { user, search, t } = this.props;

    const pageHeaderClass = classNames(
      'block page-header',
      { 'active-search': search.active }
    );

    const searchClass = classNames(
      'search',
      { 'active': search.active }
    );

    return (
      <div className={pageHeaderClass}>
        <div className="scaffold">
          <div className="logo">
            <NavLink to="/home">
              <img src={config.APP.LARGE_LOGO} width="144" height="35" />
            </NavLink>
          </div>
          <nav className="sections">
            <NavLink to="/discover/shows/all/popularity.desc">
              <span>{t('nav.series')}</span>
            </NavLink>
            <NavLink to="/discover/movies/all/popularity.desc">
              <span>{t('nav.movies')}</span>
            </NavLink>
          </nav>
          <div className="user" ref="user">
            <div className="details authenticated" onMouseEnter={this.hoverDetails} onMouseLeave={this.hoverDetails}>
              <div className="summary">
                <button className="user-name">
                  <div>{user.username}</div>
                </button>
              </div>
              <div className="dropdown">
                <div className="box-shadow">
                  <ul>
                    <li>
                      <NavLink to="/watched" className="icon watched">
                        <span>{t('watched')}</span>
                      </NavLink>
                    </li>
                    <li>
                      <NavLink to="/starred" className="icon starred">
                        <span>{t('starred')}</span>
                      </NavLink>
                    </li>
                    <li>
                      <NavLink to="/preferences" className="icon settings">
                        <span>{t('preferences')}</span>
                      </NavLink>
                    </li>
                  </ul>
                  {/*<ul>
                    <li><a href="/package" className="package">Bestil pakke</a></li>
                    <li><a href="http://kundeservice.viaplay.dk" className="customer-service">Kundeservice</a></li>
                  </ul>*/}
                  <ul className="footer">
                    <li><a className="logout" onClick={this.quitApp}>Quit</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className={searchClass} onClick={search.toggle}>
            <div className="search-icon" />
          </div>
          <div className="search-backdrop" />
        </div>
      </div>
    );
  }

}

// src/renderer/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { ipcRenderer } from 'electron';
import { Observable } from 'rxjs';

import { AppState } from '../../app-store.module';
import * as SearchActions from '../search/search.actions';
import { SearchState } from '../search';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent {

  readonly search: Observable<SearchState> = this.store.pipe(select('search'));

  hoverActive = false;

  constructor(private readonly store: Store<AppState>) {}

  toggleSearch = () => this.store.dispatch(new SearchActions().Toggle());

  hoverDetails = () => this.hoverActive = !this.hoverActive;

  quitApp = () => ipcRenderer.emit('appQuit');

}

<div class="block page-header" [class.active-search]="(search | async).active">
  <div class="scaffold">
    <div class="logo">
      <a routerLink="/">
        <img src="" width="144" height="35" />
      </a>
    </div>
    <div class="sections">
      <a routerLink="/discover/shows/all/popularity.desc">
        {{ 'nav.series' | translate }}
      </a>
      <a routerLink="/discover/movies/all/popularity.desc">
        {{ 'nav.movies' | translate }}
      </a>
    </div>
    <div class="user">
      <div class="details authenticated" (mouseenter)="hoverDetails()" (mouseleave)="hoverDetails()">
        <div class="summary">
          <button class="user-name">Username goes here</button>
        </div>
        <div class="dropdown">
          <div class="box-shadow">
            <ul>
              <li>
                <a routerLink="/watched" class="icon watched">
                  <span>{{ 'watched' | translate }}</span>
                </a>
              </li>
              <li>
                <a routerLink="/starred" class="icon starred">
                  <span>{{ 'starred' | translate }}</span>
                </a>
              </li>
              <li>
                <a routerLink="/preferences" class="icon settings">
                  <span>{{ 'preferences' | translate }}</span>
                </a>
              </li>
            </ul>
            <!--<ul>
            <li><a href="/package" class="package">Bestil pakke</a></li>
            <li><a href="http://kundeservice.viaplay.dk" class="customer-service">Kundeservice</a></li>
          </ul>-->
            <ul class="footer">
              <li><a (click)="quitApp()" class="logout">Quit</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="search" (click)="toggleSearch()" [class.active]="(search | async).active">
    <div class="search-icon"></div>
  </div>
  <div class="search-backdrop"></div>
</div>
